---
title: "🐳"
output:
  html_document:
    theme: sandstone
    css: "mystyle.css"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```
```{=html}
<style type="text/css">

body{
      font-size: 13px;
      font-family: "Anonymous Pro", "Helvetica Neue", "Roboto";
  }
</style>
```

<link rel="preconnect" href="https://fonts.googleapis.com"> <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> <link href="https://fonts.googleapis.com/css2?family=Hina+Mincho&family=Klee+One:wght@400;600&family=New+Tegomin&family=Sawarabi+Gothic&family=Shippori+Mincho+B1:wght@400;500&family=Yomogi&display=swap" rel="stylesheet"> <link rel="preconnect" href="https://fonts.googleapis.com"> <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100;300;400;500;700&display=swap" rel="stylesheet"> <link rel="preconnect" href="https://fonts.gstatic.com"> <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@100;300;400;500;700&display=swap" rel="stylesheet"> <link rel="preconnect" href="https://fonts.gstatic.com"> <link href="https://fonts.googleapis.com/css2?family=Anonymous+Pro&display=swap" rel="stylesheet"> <link href="https://fonts.googleapis.com/css2?family=Anonymous+Pro:ital,wght@0,400;1,700&display=swap" rel="stylesheet"> <link href="https://fonts.googleapis.com/css2?family=Anonymous+Pro:ital,wght@0,400;0,700;1,700&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Zen+Maru+Gothic:wght@300;400;500;600&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;1,300;1,400;1,500;1,600&display=swap" rel="stylesheet">

```{css, echo=FALSE}
@media(prefers-color-scheme: dark) {
  body {
    background-color: black;
    filter: invert(1);
  }
}
```
```{r, echo=FALSE, message=FALSE}
library(tidyverse)
library(reactable)
library(htmltools)
library(bslib)
library(dplyr)
library(purrr)
library(readr)
library(vembedr)
options(readr.show_col_types = FALSE)
```

```{r, echo=FALSE, message=FALSE, error=FALSE}
kanjinmq <- read_csv("jpdb/SCRPTNMQ-NMQ.csv")
```

Japanese Language Learning Site


<!-- ```{r, echo=FALSE, message=FALSE} -->

<!-- kanjinmq <- kanjinmq[sample(1:nrow(kanjinmq)),] -->

<!-- reactable( -->
<!--   kanjinmq, -->
<!--   columns = list( -->
<!--     Kanji = colDef( -->
<!--       cell = function(value, index) { -->
<!--         Expression <- kanjinmq$Expression[index] -->
<!--         Expression <- if (!is.na(Expression)) Expression else "" -->
<!--         Author <- kanjinmq$Author[index] -->
<!--         Author <- if (!is.na(Author)) Author else "" -->
<!--         Name <- kanjinmq$Name[index] -->
<!--         Name <- if (!is.na(Name)) Name else "" -->
<!--         Words <- kanjinmq$Words[index] -->
<!--         Words <- if (!is.na(Words)) Words else ""  -->
<!--         tagList( -->
<!--           div(style = list(fontSize = 80, fontWeight = 600, color = '#202020', fontFamily = 'Noto Sans JP'), value), -->
<!--           div(style = list(fontSize = 2), "."), -->
<!--           div(style = list(fontSize = 2), "."), -->
<!--           div(style = list(fontSize = 2), "."), -->
<!--           div(style = list(fontSize = 2), "."), -->
<!--           div(style = list(fontSize = 2), "."), -->
<!--           div(style = list(fontSize = 2), "."), -->
<!--           div(style = list(fontSize = 13, fontWeight = 600, color = '#202020', fontFamily = 'Klee One'), Expression), -->
<!--           div(style = list(fontSize = 2), "."), -->
<!--           div(style = list(fontSize = 2), "."), -->
<!--           div(style = list(fontSize = 2), "."), -->
<!--           div(style = list(fontSize = 13, fontWeight = 500, color = '#202020', fontFamily = 'Klee One'), "by: ", Author, "。", Name), -->
<!--           div(style = list(fontSize = 2), "."), -->
<!--           div(style = list(fontSize = 2), "."), -->
<!--           div(style = list(fontSize = 2), "."), -->
<!--           div(style = list(fontSize = 21, fontWeight = 600, color = '#202020', fontFamily = 'Open Sans'), Words), -->
<!--         ) -->
<!--       }, -->
<!--       align = "center" -->
<!--     ), -->
<!--     Expression = colDef(show = FALSE), -->
<!--     Author = colDef(show = FALSE), -->
<!--     Name = colDef(show = FALSE), -->
<!--     Words = colDef(show = FALSE) -->

<!--   ), -->
<!--   defaultPageSize = 1, -->
<!--   theme = reactableTheme( -->
<!--     # Vertically center cells -->
<!--     cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center", height = 400), -->
<!--     searchInputStyle = list( -->
<!--       paddingLeft = "8px", -->
<!--       paddingTop = "8px", -->
<!--       paddingBottom = "8px", -->
<!--       width = "100%" -->
<!--     ) -->
<!--   ), -->
<!--   showPageInfo = FALSE, bordered = TRUE, searchable = FALSE, sortable = FALSE, paginationType = "simple", -->

<!--   style = list(fontFamily = "Noto Sans JP, Heiti SC, Hiragino Maru Gothic ProN, Anonymous Pro , monospace, Helvetica Neue", fontSize = "11px") -->
<!-- ) -->

<!-- ``` -->

------------------------------------------------------------------------