---
title: "日本語"
output:
  html_document:
    theme: sandstone
    css: "mystyle.css"
    toc: false
    toc_float:
      collapsed: true
      smooth_scroll: true
---

```{=html}
<style type="text/css">

body{
      font-size: 13px;
      font-family: "Anonymous Pro", "Roboto", "Helvetica Neue";
  }
</style>
```
<link rel="preconnect" href="https://fonts.googleapis.com"> <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> <link href="https://fonts.googleapis.com/css2?family=Hina+Mincho&family=Klee+One:wght@400;600&family=New+Tegomin&family=Sawarabi+Gothic&family=Shippori+Mincho+B1:wght@400;500&family=Yomogi&display=swap" rel="stylesheet"> <link rel="preconnect" href="https://fonts.googleapis.com"> <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100;300;400;500;700&display=swap" rel="stylesheet"> <link rel="preconnect" href="https://fonts.gstatic.com"> <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@100;300;400;500;700&display=swap" rel="stylesheet"> <link rel="preconnect" href="https://fonts.gstatic.com"> <link href="https://fonts.googleapis.com/css2?family=Anonymous+Pro&display=swap" rel="stylesheet"> <link href="https://fonts.googleapis.com/css2?family=Anonymous+Pro:ital,wght@0,400;1,700&display=swap" rel="stylesheet"> <link href="https://fonts.googleapis.com/css2?family=Anonymous+Pro:ital,wght@0,400;0,700;1,700&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Zen+Maru+Gothic:wght@300;400;500;600&display=swap" rel="stylesheet">

```{css, echo=FALSE}
.my-tbl {
  border: 1px solid rgba(0, 0, 0, 0.1);
}

.my-header {
  border-width: 1px;
}

.my-col {
  border-right: 1px solid rgba(0, 0, 0, 0.05);
}

.my-row:hover {
  background-color: #f5f8ff;
}

.toc-content {
    padding-left: 10px;
    padding-right: 10px;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{css, echo=FALSE}
@media(prefers-color-scheme: dark) {
  body {
    background-color: black;
    filter: invert(1);
  }
}
```

```{r, echo=FALSE, message=FALSE}
library(tidyverse)
library(reactable)
library(htmltools)
library(bslib)
library(dplyr)
library(purrr)
library(readr)
library(vembedr)
options(readr.show_col_types = FALSE)
```

```{r, echo=FALSE, message=FALSE, error=FALSE}
yrcmp <- read_csv("jpdb/YRCMP-YRCMP.csv")
btkri <- read_csv("jpim/BTKRI-BTKRI.csv")
dlg1 <- read_csv("jpim/DLG1-SNT.csv")
dlg2 <- read_csv("jpim/DLG2-SNT.csv")
exrpt <- read_csv("jpim/EXRPT-SNT.csv")
psycps <- read_csv("jpim/PSYPSS-SCRPT.csv")
dlgcom <- read_csv("jpim/DLGCOM-DLG.csv")
shrty <- read_csv("jpim/SHRTSTRY-SNT.csv")
```

# <b> Immersion </b> {.tabset}
<p style="font-size:11px; line-height: 1; font-family: Noto Sans JP;  color: #202020;">**Immersion** is the act of fully submerging something within another.</p>

## <b> Series </b> {.tabset}

### S01:Yuru.Camp  {.tabset}

#### S1.EP2

```{r, echo=FALSE, message=FALSE}

yrcmp2 <- yrcmp %>% select(Script.EP2, Meaning.EP2)

reactable(
  na.omit(yrcmp2),
  columns = list(
    Script.EP2 = colDef(
      cell = function(value, index) {
        Meaning.EP2 <- yrcmp2$Meaning.EP2[index]
        Meaning.EP2 <- if (!is.na(Meaning.EP2)) Meaning.EP2 else "Unknown"
        tagList(
          div(style = list(fontSize = 16, fontWeight = 600), value),
          div(style = list(fontSize = 9, color = '#787878'), Meaning.EP2),
        )
      },
      align = "left"
    ),
    Meaning.EP2 = colDef(show = FALSE)

  ),
  defaultPageSize = 6,
  theme = reactableTheme(
    # Vertically center cells
    cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center", height = 50),
    searchInputStyle = list(
      paddingLeft = "8px",
      paddingTop = "8px",
      paddingBottom = "8px",
      width = "100%"
    )
  ),
  showPageInfo = FALSE, bordered = TRUE, searchable = TRUE, sortable = FALSE, paginationType = "numbers", outlined = TRUE, borderless = TRUE,

  style = list(fontFamily = "Noto Sans JP, Heiti SC, Hiragino Maru Gothic ProN, Anonymous Pro , monospace, Helvetica Neue", fontSize = "11px")
)

```

<!-- ------------------------------------------------------------------------ -->

#### S1.EP3

```{r, echo=FALSE, message=FALSE}

yrcmp3 <- yrcmp %>% select(Script.EP3, Meaning.EP3)

reactable(
  na.omit(yrcmp3),
  columns = list(
    Script.EP3 = colDef(
      cell = function(value, index) {
        Meaning.EP3 <- yrcmp3$Meaning.EP3[index]
        Meaning.EP3 <- if (!is.na(Meaning.EP3)) Meaning.EP3 else "Unknown"
        tagList(
          div(style = list(fontSize = 16, fontWeight = 600), value),
          div(style = list(fontSize = 9, color = '#787878'), Meaning.EP3),
        )
      },
      align = "left"
    ),
    Meaning.EP3 = colDef(show = FALSE)

  ),
  defaultPageSize = 6,
  theme = reactableTheme(
    # Vertically center cells
    cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center", height = 50),
    searchInputStyle = list(
      paddingLeft = "8px",
      paddingTop = "8px",
      paddingBottom = "8px",
      width = "100%"
    )
  ),
  showPageInfo = FALSE, bordered = TRUE, searchable = TRUE, sortable = FALSE, paginationType = "numbers", outlined = TRUE, borderless = TRUE,

  style = list(fontFamily = "Noto Sans JP, Heiti SC, Hiragino Maru Gothic ProN, Anonymous Pro , monospace, Helvetica Neue", fontSize = "11px")
)

```

<!-- ------------------------------------------------------------------------ -->

#### S1.EP4

```{r, echo=FALSE, message=FALSE}

yrcmp4 <- yrcmp %>% select(Script.EP4, Meaning.EP4)

reactable(
  na.omit(yrcmp4),
  columns = list(
    Script.EP4 = colDef(
      cell = function(value, index) {
        Meaning.EP4 <- yrcmp4$Meaning.EP4[index]
        Meaning.EP4 <- if (!is.na(Meaning.EP4)) Meaning.EP4 else "Unknown"
        tagList(
          div(style = list(fontSize = 16, fontWeight = 600), value),
          div(style = list(fontSize = 9, color = '#787878'), Meaning.EP4),
        )
      },
      align = "left"
    ),
    Meaning.EP4 = colDef(show = FALSE)

  ),
  defaultPageSize = 6,
  theme = reactableTheme(
    # Vertically center cells
    cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center", height = 50),
    searchInputStyle = list(
      paddingLeft = "8px",
      paddingTop = "8px",
      paddingBottom = "8px",
      width = "100%"
    )
  ),
  showPageInfo = FALSE, bordered = TRUE, searchable = TRUE, sortable = FALSE, paginationType = "numbers", outlined = TRUE, borderless = TRUE,

  style = list(fontFamily = "Noto Sans JP, Heiti SC, Hiragino Maru Gothic ProN, Anonymous Pro , monospace, Helvetica Neue", fontSize = "11px")
)

```

<!-- ------------------------------------------------------------------------ -->

### S02:Bottakuri {.tabset}

#### S1.EP1

```{r, echo=FALSE, message=FALSE}

btkri1 <- btkri %>% select(Script.EP1, Meaning.EP1)

reactable(
  na.omit(btkri1),
  columns = list(
    Script.EP1 = colDef(
      cell = function(value, index) {
        Meaning.EP1 <- btkri1$Meaning.EP1[index]
        Meaning.EP1 <- if (!is.na(Meaning.EP1)) Meaning.EP1 else "Unknown"
        tagList(
          div(style = list(fontSize = 16, fontWeight = 600), value),
          div(style = list(fontSize = 9, color = '#787878'), Meaning.EP1),
          # div(style = list(fontSize = 2), ".")
        )
      },
      align = "left"
    ),
    Meaning.EP1 = colDef(show = FALSE)

  ),
  defaultPageSize = 6,
  theme = reactableTheme(
    # Vertically center cells
    cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center", height = 50),
    searchInputStyle = list(
      paddingLeft = "8px",
      paddingTop = "8px",
      paddingBottom = "8px",
      width = "100%"
    )
  ),
  showPageInfo = FALSE, bordered = TRUE, searchable = TRUE, sortable = FALSE, paginationType = "numbers", outlined = TRUE, borderless = TRUE,

  style = list(fontFamily = "Noto Sans JP, Heiti SC, Hiragino Maru Gothic ProN, Anonymous Pro , monospace, Helvetica Neue", fontSize = "11px")
)

```

<!-- ------------------------------------------------------------------------ -->

#### S1.EP2

```{r, echo=FALSE, message=FALSE}

btkri2 <- btkri %>% select(Script.EP2, Meaning.EP2)

reactable(
  na.omit(btkri2),
  columns = list(
    Script.EP2 = colDef(
      cell = function(value, index) {
        Meaning.EP2 <- btkri2$Meaning.EP2[index]
        Meaning.EP2 <- if (!is.na(Meaning.EP2)) Meaning.EP2 else "Unknown"
        tagList(
          div(style = list(fontSize = 16, fontWeight = 600), value),
          div(style = list(fontSize = 9, color = '#787878'), Meaning.EP2),
          # div(style = list(fontSize = 2), ".")
        )
      },
      align = "left"
    ),
    Meaning.EP2 = colDef(show = FALSE)

  ),
  defaultPageSize = 6,
  theme = reactableTheme(
    # Vertically center cells
    cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center", height = 50),
    searchInputStyle = list(
      paddingLeft = "8px",
      paddingTop = "8px",
      paddingBottom = "8px",
      width = "100%"
    )
  ),
  showPageInfo = FALSE, bordered = TRUE, searchable = TRUE, sortable = FALSE, paginationType = "numbers", outlined = TRUE, borderless = TRUE,

  style = list(fontFamily = "Noto Sans JP, Heiti SC, Hiragino Maru Gothic ProN, Anonymous Pro , monospace, Helvetica Neue", fontSize = "11px")
)

```

<!-- ------------------------------------------------------------------------ -->

### S03:Psyco.Pass {.tabset}

#### S1.EP1

```{r, echo=FALSE, message=FALSE}

psycps.a <- psycps %>% select(Script.EP1, Meaning.EP1)

reactable(
  na.omit(psycps.a),
  columns = list(
    Script.EP1 = colDef(
      cell = function(value, index) {
        Meaning.EP1 <- psycps.a$Meaning.EP1[index]
        Meaning.EP1 <- if (!is.na(Meaning.EP1)) Meaning.EP1 else "Unknown"
        tagList(
          div(style = list(fontSize = 16, fontWeight = 600), value),
          div(style = list(fontSize = 9, color = '#787878'), Meaning.EP1),
        )
      },
      align = "left"
    ),
    Meaning.EP1 = colDef(show = FALSE)

  ),
  defaultPageSize = 6,
  theme = reactableTheme(
    # Vertically center cells
    cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center", height = 50),
    searchInputStyle = list(
      paddingLeft = "8px",
      paddingTop = "8px",
      paddingBottom = "8px",
      width = "100%"
    )
  ),
  showPageInfo = FALSE, bordered = TRUE, searchable = TRUE, sortable = FALSE, paginationType = "numbers", outlined = TRUE, borderless = TRUE,

  style = list(fontFamily = "Noto Sans JP, Heiti SC, Hiragino Maru Gothic ProN, Anonymous Pro , monospace, Helvetica Neue", fontSize = "11px")
)

```

<!-- ------------------------------------------------------------------------ -->

## <b> Dialogues </b> {.tabset}

### Japan-Life {.tabset}

#### D01:Arrival {.tabset}

```{r, echo=FALSE, message=FALSE}

dlgcom.1 <- dlgcom %>% select(Character.1, Script.1, Translation.1) %>% rename(Character = Character.1, Script = Script.1, Translation = Translation.1)

reactable(
  na.omit(dlgcom.1),
  columns = list(
    # Character = colDef(
    #   minWidth = 50,
    #   cell = function(value, index) {
    #     Script <- dlgcom.1$Script[index]
    #     Script <- if (!is.na(Script)) Script else "Unknown"
    #     Translation <- dlgcom.1$Translation[index]
    #     Translation <- if (!is.na(Translation)) Translation else "Unknown"
    #     tagList(
    #       div(style = list(fontSize = 16, fontWeight = 400), value),
    #     )
    #   },
    #   align = "left"
    # ),
    Script = colDef(
      minWidth = 300,
      cell = function(value, index) {
        Character <- dlgcom.1$Character[index]
        Character <- if (!is.na(Character)) Character else "Unknown"
        Translation <- dlgcom.1$Translation[index]
        Translation <- if (!is.na(Translation)) Translation else "Unknown"
        tagList(
          div(style = list(fontSize = 16, fontWeight = 600), value),
          div(style = list(fontSize = 9, color = '#787878'), Translation),
        )
      },
      align = "left"
    ),
    Character = colDef(show = FALSE),
    Translation = colDef(show = FALSE)

  ),
  defaultPageSize = 6,
  theme = reactableTheme(
    # Vertically center cells
    cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center", height = 50),
    searchInputStyle = list(
      paddingLeft = "8px",
      paddingTop = "8px",
      paddingBottom = "8px",
      width = "100%"
    )
  ),
  showPageInfo = FALSE, bordered = TRUE, searchable = TRUE, sortable = FALSE, paginationType = "numbers", outlined = TRUE, borderless = TRUE,

  style = list(fontFamily = "Noto Sans JP, Heiti SC, Hiragino Maru Gothic ProN, Anonymous Pro , monospace, Helvetica Neue", fontSize = "11px")
)

```

<!-- ------------------------------------------------------------------------ -->

### Restaurant {.tabset}

```{r, echo=FALSE, message=FALSE}

dlg1 <- dlg1 %>% select(Dialogue, Translation)

reactable(
  na.omit(dlg1),
  columns = list(
    Dialogue = colDef(
      cell = function(value, index) {
        Translation <- dlg1$Translation[index]
        Translation <- if (!is.na(Translation)) Translation else "Unknown"
        tagList(
          div(style = list(fontSize = 16, fontWeight = 600), value),
          div(style = list(fontSize = 9, color = '#787878'), Translation),
        )
      },
      align = "left"
    ),
    Translation = colDef(show = FALSE)

  ),
  defaultPageSize = 6,
  theme = reactableTheme(
    # Vertically center cells
    cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center", height = 50),
    searchInputStyle = list(
      paddingLeft = "8px",
      paddingTop = "8px",
      paddingBottom = "8px",
      width = "100%"
    )
  ),
  showPageInfo = FALSE, bordered = TRUE, searchable = TRUE, sortable = FALSE, paginationType = "numbers", outlined = TRUE, borderless = TRUE,

  style = list(fontFamily = "Noto Sans JP, Heiti SC, Hiragino Maru Gothic ProN, Anonymous Pro , monospace, Helvetica Neue", fontSize = "11px")
)

```

<!-- ------------------------------------------------------------------------ -->

### Icecream {.tabset}

```{r, echo=FALSE, message=FALSE}

dlg2 <- dlg2 %>% select(Dialogue, Translation)

reactable(
  na.omit(dlg2),
  columns = list(
    Dialogue = colDef(
      cell = function(value, index) {
        Translation <- dlg2$Translation[index]
        Translation <- if (!is.na(Translation)) Translation else "Unknown"
        tagList(
          div(style = list(fontSize = 16, fontWeight = 600), value),
          div(style = list(fontSize = 9, color = '#787878'), Translation),
        )
      },
      align = "left"
    ),
    Translation = colDef(show = FALSE)

  ),
  defaultPageSize = 6,
  theme = reactableTheme(
    # Vertically center cells
    cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center", height = 50),
    searchInputStyle = list(
      paddingLeft = "8px",
      paddingTop = "8px",
      paddingBottom = "8px",
      width = "100%"
    )
  ),
  showPageInfo = FALSE, bordered = TRUE, searchable = TRUE, sortable = FALSE, paginationType = "numbers", outlined = TRUE, borderless = TRUE,

  style = list(fontFamily = "Noto Sans JP, Heiti SC, Hiragino Maru Gothic ProN, Anonymous Pro , monospace, Helvetica Neue", fontSize = "11px")
)

```

<!-- ------------------------------------------------------------------------ -->

## <b> Exerpts </b> {.tabset}

### E01 {.tabset}

```{r, echo=FALSE, message=FALSE}

exrpt <- exrpt[sample(1:nrow(exrpt)),]
exrpt.a <- exrpt  %>% slice(1:1)

reactable(
  exrpt.a,
  columns = list(
    Script = colDef(
      minWidth = 280,
      cell = function(value, index) {
        Translation <- exrpt.a$Translation[index]
        Translation <- if (!is.na(Translation)) Translation else ""
        tagList(
          div(style = list(fontSize = 20, fontWeight = 400, color = '#202020', fontFamily = 'Zen Maru Gothic'), value),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 12, fontWeight = 300, color = '#202020', fontFamily = 'Klee One'), Translation),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
        )
      },
      align = "left"
    ),
    Translation = colDef(show = FALSE)

  ),
  defaultPageSize = 1,
  theme = reactableTheme(
    # Vertically center cells
    cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center"),
    searchInputStyle = list(
      paddingLeft = "8px",
      paddingTop = "8px",
      paddingBottom = "8px",
      width = "100%"
    )
  ),
  showPageInfo = FALSE, bordered = TRUE, searchable = TRUE, sortable = FALSE, paginationType = "simple",
  
  style = list(fontFamily = "Noto Sans JP, Heiti SC, Hiragino Maru Gothic ProN, Anonymous Pro , monospace, Helvetica Neue", fontSize = "11px")
)

```

<h6> </h6>

<!-- ------------------------------------------------------------------------ -->

### E02 {.tabset}

```{r, echo=FALSE, message=FALSE}

exrpt.a <- exrpt  %>% slice(2:2)

reactable(
  exrpt.a,
  columns = list(
    Script = colDef(
      minWidth = 280,
      cell = function(value, index) {
        Translation <- exrpt.a$Translation[index]
        Translation <- if (!is.na(Translation)) Translation else ""
        tagList(
          div(style = list(fontSize = 20, fontWeight = 400, color = '#202020', fontFamily = 'Zen Maru Gothic'), value),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 12, fontWeight = 300, color = '#202020', fontFamily = 'Klee One'), Translation),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
        )
      },
      align = "left"
    ),
    Translation = colDef(show = FALSE)

  ),
  defaultPageSize = 1,
  theme = reactableTheme(
    # Vertically center cells
    cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center"),
    searchInputStyle = list(
      paddingLeft = "8px",
      paddingTop = "8px",
      paddingBottom = "8px",
      width = "100%"
    )
  ),
  showPageInfo = FALSE, bordered = TRUE, searchable = TRUE, sortable = FALSE, paginationType = "simple",
  
  style = list(fontFamily = "Noto Sans JP, Heiti SC, Hiragino Maru Gothic ProN, Anonymous Pro , monospace, Helvetica Neue", fontSize = "11px")
)

```

<h6> </h6>

<!-- ------------------------------------------------------------------------ -->

## <b> Stories </b> {.tabset}

### S01 {.tabset}

```{r, echo=FALSE, message=FALSE}

shrty <- shrty[sample(1:nrow(shrty)),]
shrty.a <- shrty  %>% slice(1:1)

reactable(
  shrty.a,
  columns = list(
    Script = colDef(
      minWidth = 280,
      cell = function(value, index) {
        Translation <- shrty.a$Translation[index]
        Translation <- if (!is.na(Translation)) Translation else ""
        tagList(
          div(style = list(fontSize = 20, fontWeight = 400, color = '#202020', fontFamily = 'Zen Maru Gothic'), value),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 12, fontWeight = 300, color = '#202020', fontFamily = 'Klee One'), Translation),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
        )
      },
      align = "left"
    ),
    Translation = colDef(show = FALSE)

  ),
  defaultPageSize = 1,
  theme = reactableTheme(
    # Vertically center cells
    cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center"),
    searchInputStyle = list(
      paddingLeft = "8px",
      paddingTop = "8px",
      paddingBottom = "8px",
      width = "100%"
    )
  ),
  showPageInfo = FALSE, bordered = TRUE, searchable = TRUE, sortable = FALSE, paginationType = "simple",
  
  style = list(fontFamily = "Noto Sans JP, Heiti SC, Hiragino Maru Gothic ProN, Anonymous Pro , monospace, Helvetica Neue", fontSize = "11px")
)

```

<h6> </h6>

<!-- ------------------------------------------------------------------------ -->

### S02 {.tabset}

```{r, echo=FALSE, message=FALSE}

shrty.a <- shrty  %>% slice(2:2)

reactable(
  shrty.a,
  columns = list(
    Script = colDef(
      minWidth = 280,
      cell = function(value, index) {
        Translation <- shrty.a$Translation[index]
        Translation <- if (!is.na(Translation)) Translation else ""
        tagList(
          div(style = list(fontSize = 20, fontWeight = 400, color = '#202020', fontFamily = 'Zen Maru Gothic'), value),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 12, fontWeight = 300, color = '#202020', fontFamily = 'Klee One'), Translation),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
        )
      },
      align = "left"
    ),
    Translation = colDef(show = FALSE)

  ),
  defaultPageSize = 1,
  theme = reactableTheme(
    # Vertically center cells
    cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center"),
    searchInputStyle = list(
      paddingLeft = "8px",
      paddingTop = "8px",
      paddingBottom = "8px",
      width = "100%"
    )
  ),
  showPageInfo = FALSE, bordered = TRUE, searchable = TRUE, sortable = FALSE, paginationType = "simple",
  
  style = list(fontFamily = "Noto Sans JP, Heiti SC, Hiragino Maru Gothic ProN, Anonymous Pro , monospace, Helvetica Neue", fontSize = "11px")
)

```

<h6> </h6>

<!-- ------------------------------------------------------------------------ -->

### S03 {.tabset}

```{r, echo=FALSE, message=FALSE}

shrty.a <- shrty  %>% slice(3:3)

reactable(
  shrty.a,
  columns = list(
    Script = colDef(
      minWidth = 280,
      cell = function(value, index) {
        Translation <- shrty.a$Translation[index]
        Translation <- if (!is.na(Translation)) Translation else ""
        tagList(
          div(style = list(fontSize = 20, fontWeight = 400, color = '#202020', fontFamily = 'Zen Maru Gothic'), value),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 12, fontWeight = 300, color = '#202020', fontFamily = 'Klee One'), Translation),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
          div(style = list(fontSize = 2), "."),
        )
      },
      align = "left"
    ),
    Translation = colDef(show = FALSE)

  ),
  defaultPageSize = 1,
  theme = reactableTheme(
    # Vertically center cells
    cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center"),
    searchInputStyle = list(
      paddingLeft = "8px",
      paddingTop = "8px",
      paddingBottom = "8px",
      width = "100%"
    )
  ),
  showPageInfo = FALSE, bordered = TRUE, searchable = TRUE, sortable = FALSE, paginationType = "simple",
  
  style = list(fontFamily = "Noto Sans JP, Heiti SC, Hiragino Maru Gothic ProN, Anonymous Pro , monospace, Helvetica Neue", fontSize = "11px")
)

```

<h6> </h6>

<!-- ------------------------------------------------------------------------ -->