---
title: "日本語"
output:
  html_document:
    theme: sandstone
    css: "mystyle.css"
    toc: false
    toc_float:
      collapsed: false
      smooth_scroll: true
---

```{=html}
<style type="text/css">

body{
      font-size: 13px;
      font-family: "Anonymous Pro", "Roboto", "Helvetica Neue";
  }
</style>
```
<link rel="preconnect" href="https://fonts.googleapis.com"> <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> <link href="https://fonts.googleapis.com/css2?family=Hina+Mincho&family=Klee+One:wght@400;600&family=New+Tegomin&family=Sawarabi+Gothic&family=Shippori+Mincho+B1:wght@400;500&family=Yomogi&display=swap" rel="stylesheet"> <link rel="preconnect" href="https://fonts.googleapis.com"> <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100;300;400;500;700&display=swap" rel="stylesheet"> <link rel="preconnect" href="https://fonts.gstatic.com"> <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@100;300;400;500;700&display=swap" rel="stylesheet"> <link rel="preconnect" href="https://fonts.gstatic.com"> <link href="https://fonts.googleapis.com/css2?family=Anonymous+Pro&display=swap" rel="stylesheet"> <link href="https://fonts.googleapis.com/css2?family=Anonymous+Pro:ital,wght@0,400;1,700&display=swap" rel="stylesheet"> <link href="https://fonts.googleapis.com/css2?family=Anonymous+Pro:ital,wght@0,400;0,700;1,700&display=swap" rel="stylesheet">

```{css, echo=FALSE}
.my-tbl {
  border: 1px solid rgba(0, 0, 0, 0.1);
}

.my-header {
  border-width: 1px;
}

.my-col {
  border-right: 1px solid rgba(0, 0, 0, 0.05);
}

.my-row:hover {
  background-color: #f5f8ff;
}

.toc-content {
    padding-left: 10px;
    padding-right: 10px;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{css, echo=FALSE}
@media(prefers-color-scheme: dark) {
  body {
    background-color: black;
    filter: invert(1);
  }
}
```

```{r, echo=FALSE, message=FALSE}
library(tidyverse)
library(reactable)
library(htmltools)
library(bslib)
library(dplyr)
library(purrr)
library(readr)
library(vembedr)
options(readr.show_col_types = FALSE)
```

```{r, echo=FALSE, message=FALSE, error=FALSE}
vnstx <- read_csv("vrbjp/Sheet 178-VNLST.csv")
vnstb <- read_csv("vrbjp/Sheet 83-VBPH.csv")
vnstc <- read_csv("vrbjp/Sheet 148-SSTNC.csv")
vnstd <- read_csv("vrbjp/Sheet 149-SSTNC.csv")
vnste <- read_csv("vrbjp/Sheet 150-SSTNC.csv")
vnstg <- read_csv("vrbjp/Sheet 2-VGRM.csv")
vnsgg <- read_csv("vrbjp/Sheet 3-VGRM.csv")
vnsss <- read_csv("vrbjp/Sheet 1-VBPLS.csv")
knj <- read_csv("vrbjp/Sheet 5-KNJ.csv")
knjr <- read_csv("vrbjp/Sheet 6-KNJ.csv")
vnsst <- read_csv("vrbjp/Sheet 7-VPHS.csv")
klvl1 <- read_csv("vrbjp/Sheet 8-WBKNJ1.csv")
klvl2 <- read_csv("vrbjp/Sheet 9-WBKNJ2.csv")
klvl3 <- read_csv("vrbjp/Sheet 10-WBKNJ3.csv")
klv1 <- read_csv("vrbjp/Sheet 11-KNJD1.csv")
klv2 <- read_csv("vrbjp/Sheet 12-KNJD2.csv")
vnlr <- read_csv("vrbjp/Sheet 14-VNLST.csv")
dlgm <- read_csv("vrbjp/Sheet 13-TBE.csv")
nlgm <- read_csv("vrbjp/Sheet 15-JGRM.csv")
jlgm <- read_csv("vrbjp/Sheet 16-JGRM.csv")
mnlg <- read_csv("vrbjp/Sheet 17-MNLNG.csv")
onmp <- read_csv("vrbjp/Sheet 18-ONMP.csv")
cnmw <- read_csv("vrbjp/Sheet 19-CMNW.csv")
cnmw1 <- read_csv("vrbjp/Sheet 22-CMNW.csv")
cnmw2 <- read_csv("vrbjp/Sheet 23-CMNW.csv")
cnmw3 <- read_csv("vrbjp/Sheet 24-CMNW.csv")
cnmw4 <- read_csv("vrbjp/Sheet 25-CMNW.csv")
cnmw5 <- read_csv("vrbjp/Sheet 26-CMNW.csv")
cnmw6 <- read_csv("vrbjp/Sheet 27-CMNW.csv")
cmpnd <- read_csv("vrbjp/Sheet 35-CMPWD.csv")
cook <- read_csv("vrbjp/Sheet 20-MKOKT.csv")
diary <- read_csv("vrbjp/Sheet 21-FTRD.csv")
knjdl<- read_csv("vrbjp/Sheet 40-KNJD.csv")
expw<- read_csv("vrbjp/Sheet 36-EXPR.csv")
adjadv<- read_csv("vrbjp/Sheet 37-ADVADJ.csv")
cmwrdsn<- read_csv("vrbjp/Sheet 43-CMNWP.csv")
exppw<- read_csv("vrbjp/Sheet 42-EXPRP.csv")
jnrst <- read_csv("vrbjp/Sheet 44-JNRST.csv")
sntv <- read_csv("vrbjp/Sheet 98-MSNTC.csv")
rvvrb <- read_csv("vrbjp/Sheet 179-VNLST.csv")
rvwrd <- read_csv("vrbjp/Sheet 180-WRDSR.csv")
rvsnt <- read_csv("vrbjp/Sheet 181-WRDST.csv")
knjrvw <- read_csv("vrbjp/Sheet 50-WBKNRN.csv")
knjwrdx <- read_csv("vrbjp/Sheet 51-KNJWRD.csv")
icwrds <- read_csv("vrbjp/Sheet 128-VBPRHS.csv")
lvlg2 <- read_csv("vrbjp/Sheet 52-LVLGR.csv")
kjpen <- read_csv("vrbjp/Sheet 34-KJPEN.csv")
cmnknj <- read_csv("vrbjp/Sheet 70-CMKNJ.csv")
cmnknjv <- read_csv("vrbjp/Sheet 80-CMKNJV.csv")
cmnknjp <- read_csv("vrbjp/Sheet 81-CMKNJW.csv")
cmwpf <- read_csv("vrbjp/Sheet 90-CMKNJVM.csv")
cmwpg <- read_csv("vrbjp/Sheet 92-VGRM.csv")
cmwpc <- read_csv("vrbjp/Sheet 46-SSTBLM.csv")
cmwpu <- read_csv("vrbjp/Sheet 93-CMKNJVM.csv")
cmwpd <- read_csv("vrbjp/Sheet 95-CMKNJVM.csv")
cmwpe <- read_csv("vrbjp/Sheet 96-CMKNJVM.csv")
cmwpd2 <- read_csv("vrbjp/Sheet 97-CMKNJVM.csv")
cmwcpd <- read_csv("vrbjp/Sheet 49-WRDSCMN.csv")
fkanji <- read_csv("vrbjp/FRKJN-FREQ.csv")
ckanji <- read_csv("vrbjp/CKJN-KNJ.csv")
fwkanji <- read_csv("vrbjp/FRWKJN-FREQ.csv")
smpsnt <- read_csv("vrbjp/SMSNT-SNT.csv")
expspk <- read_csv("vrbjp/Sheet 77-ESNEXP.csv")
knjlst1 <- read_csv("vrbjp/KNJ1-WBKNJ1.csv")
knjlst2 <- read_csv("vrbjp/KNJ2-WBKNJ2.csv")
knjlst3 <- read_csv("vrbjp/KNJ3-WBKNJ3.csv")
knjlst4 <- read_csv("vrbjp/KNJ4-WBKNJ4.csv")
knjlst5 <- read_csv("vrbjp/KNJ5-WBKNJ5.csv")
knjlstr <- read_csv("vrbjp/KNJR-RNDMWV.csv")
spphr <- read_csv("vrbjp/SPPHR-HLPRS.csv")
chnkw <- read_csv("vrbjp/CHNK-RLWRD.csv")
lverbs <- read_csv("vrbjp/VERBS-VRBRNK.csv")
scknj5 <- read_csv("vrbjp/SKNJN5-KNJD1.csv")
scknj4 <- read_csv("vrbjp/SKNJN4-KNJD2.csv")
scknj3 <- read_csv("vrbjp/SKNJN3-KNJD3.csv")
scknj2 <- read_csv("vrbjp/SKNJN2-KNJD4.csv")
scknj1 <- read_csv("vrbjp/SKNJN1-KNJD5.csv")
nadj1 <- read_csv("vrbjp/ADJL-NAADJ1.csv")
nadj2 <- read_csv("vrbjp/ADJI-IADJ1.csv")
adv1 <- read_csv("vrbjp/ADV-ADV1.csv")
v1hme <- read_csv("vrbjp/CATG-VCBT1.csv")
v1hme <- read_csv("vrbjp/CATG-VCBT1.csv")
wrd5ex <- read_csv("vrbjp/WRDN5-WRD5.csv")
wrd4ex <- read_csv("vrbjp/WRDN4-WRD4.csv")
wrd3ex <- read_csv("vrbjp/WRDN3-WRD3.csv")
wrd2ex <- read_csv("vrbjp/WRDN2-WRD2.csv")
wrd1ex <- read_csv("vrbjp/WRDN1-WRD1.csv")
qsn5 <- read_csv("vrbjp/QSNTN5-QSNT5.csv")
qsn4 <- read_csv("vrbjp/QSNTN4-QSNT4.csv")
qsn3 <- read_csv("vrbjp/QSNTN3-QSNT3.csv")
qsn2 <- read_csv("vrbjp/QSNTN2-QSNT2.csv")
qsn1 <- read_csv("vrbjp/QSNTN1-QSNT1.csv")
knjcmm <- read_csv("vrbjp/CMPCH-KNJCMM.csv")
jyknj <- read_csv("vrbjp/JYKNJ-JYKNJI.csv")
jyknjon <- read_csv("vrbjp/JYKNJS-JYKNJI.csv")
jyknjkn <- read_csv("vrbjp/JYKNJK-JYKNJI.csv")
wrcll <- read_csv("vrbjp/RCLL-RCLL.csv")
shpe <- read_csv("vrbjp/SHPE-SHPE.csv")
vusge <- read_csv("vrbjp/VUSGE-VUSGE.csv")
kjlpt <- read_csv("vrbjp/JLPTW-PTWRD.csv")
wjlpt <- read_csv("vrbjp/JLPTWR-PTWRDS.csv")
grphrs <- read_csv("vrbjp/GRPHR-GRMPH.csv")
vwrbst <- read_csv("vrbjp/WVRBSH-WVBRN.csv")
tnkwrd <- read_csv("vrbjp/WTNK-WRDS.csv")
cmnvrb <- read_csv("vrbjp/CMVRB-CMVRB.csv")
sylvrb <- read_csv("vrbjp/WVRBSYL-WVBSYL.csv")
vrcll <- read_csv("vrbjp/VRCLL-WVBRN.csv")
vrbxt <- read_csv("vrbjp/VRBXT-VWRBXT.csv")
dlyknj <- read_csv("vrbjp/DLYKNJ-JYKDL.csv")
bscknj <- read_csv("vrbjp/BSCKNJ-JYKDL.csv")
vrbrvws <- read_csv("vrbjp/VRWK-KRVW.csv")
ivrbs <- read_csv("vrbjp/IVRBS-IVRBS.csv")
gvrbs <- read_csv("vrbjp/GVRBS-GVRBS.csv")
vfrsyl <- read_csv("vrbjp/WVFRSYL-WVBRN.csv")
corew <- read_csv("vrbjp/CRWRD-CRSWRD.csv")
sndknj <- read_csv("vrbjp/KNSND-KNSND.csv")
vrbxte <- read_csv("vrbjp/VRBXTE-VWRBXT.csv")
mem <- read_csv("vrbjp/MEM-MEM.csv")
dct <- read_csv("vrbjp/DCT-MEM.csv")
kana <- read_csv("vrbjp/KANA-CHR.csv")
kcmb <- read_csv("vrbjp/CMBD-CHR.csv")
verbrw <- read_csv("vrbjp/VRBRVS-WRB.csv")
dictny <- read_csv("vrbjp/DCTNY-MEM.csv")
wrdmm <- read_csv("vrbjp/WRDMM-MEM.csv")
exwrd <- read_csv("vrbjp/EXRVW-EXWRD.csv")
mcmndc <- read_csv("vrbjp/MNWRDC-CMNWRDS.csv")
tchwrd <- read_csv("vrbjp/TCWRDS-NWRDS.csv")
expvcb <- read_csv("vrbjp/EXPTB-EXPTB.csv")
skmscn <- read_csv("vrbjp/SKMSCN-SKSC.csv")
cvnptn <- read_csv("vrbjp/PTRNLST-GRML.csv")
knjrndx <- read_csv("vrbjp/RNMDKNJX-TBL.csv")
dlywrds <- read_csv("vrbjp/DLYWD-TBL.csv")
mwrdslvl <- read_csv("vrbjp/JLPTWD-JLPT.csv")
spksnt <- read_csv("vrbjp/SPKSNT-TBLSNT.csv")
vrbrwq <- read_csv("vrbjp/VRBRVWS-VRB.csv")
```

# Words {.tabset}

## Level {.tabset}

### L5 {.tabset}

<div class = "row">
<div class = "col-sm-4">

```{r, echo=FALSE, message=FALSE}

mwrdslvl5 <- mwrdslvl %>% slice(1:2053)

reactable(
  mwrdslvl5,
  columns = list(
    Expression = colDef(
      cell = function(value, index) {
        Reading <- mwrdslvl5$Reading[index]
        Reading <- if (!is.na(Reading)) Reading else ""
        Meaning <- mwrdslvl5$Meaning[index]
        Meaning <- if (!is.na(Meaning)) Meaning else ""
        tagList(
          div(style = list(fontSize = 30, fontWeight = 600), value),
          div(style = list(fontSize = 9), Reading),
          div(style = list(fontSize = 9, fontWeight = 500), Meaning),
        )
      },
      align = "center"
    ),

    Reading = colDef(show = FALSE),
    Meaning = colDef(show = FALSE)

  ),
  defaultPageSize = 1,
  theme = reactableTheme(
    # Vertically center cells
    cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center", height = 250),
    searchInputStyle = list(
      paddingLeft = "8px",
      paddingTop = "8px",
      paddingBottom = "8px",
      width = "100%"
    )
  ),
  showPageInfo = FALSE, bordered = TRUE, searchable = TRUE, sortable = FALSE, paginationType = "simple",

  style = list(fontFamily = "Noto Sans JP, Heiti SC, Hiragino Maru Gothic ProN, Anonymous Pro , monospace, Helvetica Neue", fontSize = "11px")
)

```

</div>
<div class = "col-sm-8">

```{r, echo=FALSE, message=FALSE}

mwrdslvl5 <- mwrdslvl5[sample(1:nrow(mwrdslvl5)),]

reactable(
  mwrdslvl5,
  columns = list(
    Expression = colDef(
      cell = function(value, index) {
        Reading <- mwrdslvl5$Reading[index]
        Reading <- if (!is.na(Reading)) Reading else ""
        Meaning <- mwrdslvl5$Meaning[index]
        Meaning <- if (!is.na(Meaning)) Meaning else ""
        tagList(
          div(style = list(fontSize = 30, fontWeight = 600), value),
          # div(style = list(fontSize = 9), Reading),
          # div(style = list(fontSize = 8), Meaning),
        )
      },
      align = "center"
    ),

    Reading = colDef(show = FALSE),
    Meaning = colDef(show = FALSE)

  ),
  defaultPageSize = 1,
  theme = reactableTheme(
    # Vertically center cells
    cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center", height = 250),
    searchInputStyle = list(
      paddingLeft = "8px",
      paddingTop = "8px",
      paddingBottom = "8px",
      width = "100%"
    )
  ),
  showPageInfo = FALSE, bordered = TRUE, searchable = TRUE, sortable = FALSE, paginationType = "simple",

  style = list(fontFamily = "Noto Sans JP, Heiti SC, Hiragino Maru Gothic ProN, Anonymous Pro , monospace, Helvetica Neue", fontSize = "11px")
)

```

</div>
</div>

------------------------------------------------------------------------

### L4 {.tabset}

<div class = "row">
<div class = "col-sm-4">

```{r, echo=FALSE, message=FALSE}

mwrdslvl4 <- mwrdslvl %>% slice(2054:2722)

reactable(
  mwrdslvl4,
  columns = list(
    Expression = colDef(
      cell = function(value, index) {
        Reading <- mwrdslvl4$Reading[index]
        Reading <- if (!is.na(Reading)) Reading else ""
        Meaning <- mwrdslvl4$Meaning[index]
        Meaning <- if (!is.na(Meaning)) Meaning else ""
        tagList(
          div(style = list(fontSize = 30, fontWeight = 600), value),
          div(style = list(fontSize = 9), Reading),
          div(style = list(fontSize = 9, fontWeight = 500), Meaning),
        )
      },
      align = "center"
    ),

    Reading = colDef(show = FALSE),
    Meaning = colDef(show = FALSE)

  ),
  defaultPageSize = 1,
  theme = reactableTheme(
    # Vertically center cells
    cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center", height = 250),
    searchInputStyle = list(
      paddingLeft = "8px",
      paddingTop = "8px",
      paddingBottom = "8px",
      width = "100%"
    )
  ),
  showPageInfo = FALSE, bordered = TRUE, searchable = TRUE, sortable = FALSE, paginationType = "simple",

  style = list(fontFamily = "Noto Sans JP, Heiti SC, Hiragino Maru Gothic ProN, Anonymous Pro , monospace, Helvetica Neue", fontSize = "11px")
)

```

</div>
<div class = "col-sm-8">

```{r, echo=FALSE, message=FALSE}

mwrdslvl4 <- mwrdslvl4[sample(1:nrow(mwrdslvl4)),]

reactable(
  mwrdslvl4,
  columns = list(
    Expression = colDef(
      cell = function(value, index) {
        Reading <- mwrdslvl4$Reading[index]
        Reading <- if (!is.na(Reading)) Reading else ""
        Meaning <- mwrdslvl4$Meaning[index]
        Meaning <- if (!is.na(Meaning)) Meaning else ""
        tagList(
          div(style = list(fontSize = 30, fontWeight = 600), value),
          # div(style = list(fontSize = 9), Reading),
          # div(style = list(fontSize = 8), Meaning),
        )
      },
      align = "center"
    ),

    Reading = colDef(show = FALSE),
    Meaning = colDef(show = FALSE)

  ),
  defaultPageSize = 1,
  theme = reactableTheme(
    # Vertically center cells
    cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center", height = 250),
    searchInputStyle = list(
      paddingLeft = "8px",
      paddingTop = "8px",
      paddingBottom = "8px",
      width = "100%"
    )
  ),
  showPageInfo = FALSE, bordered = TRUE, searchable = TRUE, sortable = FALSE, paginationType = "simple",

  style = list(fontFamily = "Noto Sans JP, Heiti SC, Hiragino Maru Gothic ProN, Anonymous Pro , monospace, Helvetica Neue", fontSize = "11px")
)

```

</div>
</div>

------------------------------------------------------------------------

### L3 {.tabset}

<div class = "row">
<div class = "col-sm-4">

```{r, echo=FALSE, message=FALSE}

mwrdslvl3 <- mwrdslvl %>% slice(2723:4861)

reactable(
  mwrdslvl3,
  columns = list(
    Expression = colDef(
      cell = function(value, index) {
        Reading <- mwrdslvl3$Reading[index]
        Reading <- if (!is.na(Reading)) Reading else ""
        Meaning <- mwrdslvl3$Meaning[index]
        Meaning <- if (!is.na(Meaning)) Meaning else ""
        tagList(
          div(style = list(fontSize = 30, fontWeight = 600), value),
          div(style = list(fontSize = 9), Reading),
          div(style = list(fontSize = 9, fontWeight = 500), Meaning),
        )
      },
      align = "center"
    ),

    Reading = colDef(show = FALSE),
    Meaning = colDef(show = FALSE)

  ),
  defaultPageSize = 1,
  theme = reactableTheme(
    # Vertically center cells
    cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center", height = 250),
    searchInputStyle = list(
      paddingLeft = "8px",
      paddingTop = "8px",
      paddingBottom = "8px",
      width = "100%"
    )
  ),
  showPageInfo = FALSE, bordered = TRUE, searchable = TRUE, sortable = FALSE, paginationType = "simple",

  style = list(fontFamily = "Noto Sans JP, Heiti SC, Hiragino Maru Gothic ProN, Anonymous Pro , monospace, Helvetica Neue", fontSize = "11px")
)

```

</div>
<div class = "col-sm-8">

```{r, echo=FALSE, message=FALSE}

mwrdslvl3 <- mwrdslvl3[sample(1:nrow(mwrdslvl3)),]

reactable(
  mwrdslvl3,
  columns = list(
    Expression = colDef(
      cell = function(value, index) {
        Reading <- mwrdslvl3$Reading[index]
        Reading <- if (!is.na(Reading)) Reading else ""
        Meaning <- mwrdslvl3$Meaning[index]
        Meaning <- if (!is.na(Meaning)) Meaning else ""
        tagList(
          div(style = list(fontSize = 30, fontWeight = 600), value),
          # div(style = list(fontSize = 9), Reading),
          # div(style = list(fontSize = 8), Meaning),
        )
      },
      align = "center"
    ),

    Reading = colDef(show = FALSE),
    Meaning = colDef(show = FALSE)

  ),
  defaultPageSize = 1,
  theme = reactableTheme(
    # Vertically center cells
    cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center", height = 250),
    searchInputStyle = list(
      paddingLeft = "8px",
      paddingTop = "8px",
      paddingBottom = "8px",
      width = "100%"
    )
  ),
  showPageInfo = FALSE, bordered = TRUE, searchable = TRUE, sortable = FALSE, paginationType = "simple",

  style = list(fontFamily = "Noto Sans JP, Heiti SC, Hiragino Maru Gothic ProN, Anonymous Pro , monospace, Helvetica Neue", fontSize = "11px")
)

```

</div>
</div>

------------------------------------------------------------------------

### L2 {.tabset}

<div class = "row">
<div class = "col-sm-4">

```{r, echo=FALSE, message=FALSE}

mwrdslvl2 <- mwrdslvl %>% slice(4862:6609)

reactable(
  mwrdslvl2,
  columns = list(
    Expression = colDef(
      cell = function(value, index) {
        Reading <- mwrdslvl2$Reading[index]
        Reading <- if (!is.na(Reading)) Reading else ""
        Meaning <- mwrdslvl2$Meaning[index]
        Meaning <- if (!is.na(Meaning)) Meaning else ""
        tagList(
          div(style = list(fontSize = 30, fontWeight = 600), value),
          div(style = list(fontSize = 9), Reading),
          div(style = list(fontSize = 9, fontWeight = 500), Meaning),
        )
      },
      align = "center"
    ),

    Reading = colDef(show = FALSE),
    Meaning = colDef(show = FALSE)

  ),
  defaultPageSize = 1,
  theme = reactableTheme(
    # Vertically center cells
    cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center", height = 250),
    searchInputStyle = list(
      paddingLeft = "8px",
      paddingTop = "8px",
      paddingBottom = "8px",
      width = "100%"
    )
  ),
  showPageInfo = FALSE, bordered = TRUE, searchable = TRUE, sortable = FALSE, paginationType = "simple",

  style = list(fontFamily = "Noto Sans JP, Heiti SC, Hiragino Maru Gothic ProN, Anonymous Pro , monospace, Helvetica Neue", fontSize = "11px")
)

```

</div>
<div class = "col-sm-8">

```{r, echo=FALSE, message=FALSE}

mwrdslvl2 <- mwrdslvl2[sample(1:nrow(mwrdslvl2)),]

reactable(
  mwrdslvl2,
  columns = list(
    Expression = colDef(
      cell = function(value, index) {
        Reading <- mwrdslvl2$Reading[index]
        Reading <- if (!is.na(Reading)) Reading else ""
        Meaning <- mwrdslvl2$Meaning[index]
        Meaning <- if (!is.na(Meaning)) Meaning else ""
        tagList(
          div(style = list(fontSize = 30, fontWeight = 600), value),
          # div(style = list(fontSize = 9), Reading),
          # div(style = list(fontSize = 8), Meaning),
        )
      },
      align = "center"
    ),

    Reading = colDef(show = FALSE),
    Meaning = colDef(show = FALSE)

  ),
  defaultPageSize = 1,
  theme = reactableTheme(
    # Vertically center cells
    cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center", height = 250),
    searchInputStyle = list(
      paddingLeft = "8px",
      paddingTop = "8px",
      paddingBottom = "8px",
      width = "100%"
    )
  ),
  showPageInfo = FALSE, bordered = TRUE, searchable = TRUE, sortable = FALSE, paginationType = "simple",

  style = list(fontFamily = "Noto Sans JP, Heiti SC, Hiragino Maru Gothic ProN, Anonymous Pro , monospace, Helvetica Neue", fontSize = "11px")
)

```

</div>
</div>

------------------------------------------------------------------------

### L1 {.tabset}

<div class = "row">
<div class = "col-sm-4">

```{r, echo=FALSE, message=FALSE}

mwrdslvl1 <- mwrdslvl %>% slice(6610:9307)

reactable(
  mwrdslvl1,
  columns = list(
    Expression = colDef(
      cell = function(value, index) {
        Reading <- mwrdslvl1$Reading[index]
        Reading <- if (!is.na(Reading)) Reading else ""
        Meaning <- mwrdslvl1$Meaning[index]
        Meaning <- if (!is.na(Meaning)) Meaning else ""
        tagList(
          div(style = list(fontSize = 30, fontWeight = 600), value),
          div(style = list(fontSize = 9), Reading),
          div(style = list(fontSize = 9, fontWeight = 500), Meaning),
        )
      },
      align = "center"
    ),

    Reading = colDef(show = FALSE),
    Meaning = colDef(show = FALSE)

  ),
  defaultPageSize = 1,
  theme = reactableTheme(
    # Vertically center cells
    cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center", height = 250),
    searchInputStyle = list(
      paddingLeft = "8px",
      paddingTop = "8px",
      paddingBottom = "8px",
      width = "100%"
    )
  ),
  showPageInfo = FALSE, bordered = TRUE, searchable = TRUE, sortable = FALSE, paginationType = "simple",

  style = list(fontFamily = "Noto Sans JP, Heiti SC, Hiragino Maru Gothic ProN, Anonymous Pro , monospace, Helvetica Neue", fontSize = "11px")
)

```

</div>
<div class = "col-sm-8">

```{r, echo=FALSE, message=FALSE}

mwrdslvl1 <- mwrdslvl1[sample(1:nrow(mwrdslvl1)),]

reactable(
  mwrdslvl1,
  columns = list(
    Expression = colDef(
      cell = function(value, index) {
        Reading <- mwrdslvl1$Reading[index]
        Reading <- if (!is.na(Reading)) Reading else ""
        Meaning <- mwrdslvl1$Meaning[index]
        Meaning <- if (!is.na(Meaning)) Meaning else ""
        tagList(
          div(style = list(fontSize = 30, fontWeight = 600), value),
          # div(style = list(fontSize = 9), Reading),
          # div(style = list(fontSize = 8), Meaning),
        )
      },
      align = "center"
    ),

    Reading = colDef(show = FALSE),
    Meaning = colDef(show = FALSE)

  ),
  defaultPageSize = 1,
  theme = reactableTheme(
    # Vertically center cells
    cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center", height = 250),
    searchInputStyle = list(
      paddingLeft = "8px",
      paddingTop = "8px",
      paddingBottom = "8px",
      width = "100%"
    )
  ),
  showPageInfo = FALSE, bordered = TRUE, searchable = TRUE, sortable = FALSE, paginationType = "simple",

  style = list(fontFamily = "Noto Sans JP, Heiti SC, Hiragino Maru Gothic ProN, Anonymous Pro , monospace, Helvetica Neue", fontSize = "11px")
)

```

</div>
</div>

------------------------------------------------------------------------

## Category {.tabset}

------------------------------------------------------------------------

## Daily {.tabset}

### Core {.tabset}

<div class = "row">
<div class = "col-sm-4">

```{r, echo=FALSE, message=FALSE}

corewx <- corew %>% slice(1:200) %>% rename(Sentences = S1)
corewx <- corewx[sample(1:nrow(corewx)),]

reactable(
  corewx,
  columns = list(
    Words = colDef(
      # Show species under character names
      cell = function(value, index) {
        Reading <- corewx$Reading[index]
        Reading <- if (!is.na(Reading)) Reading else ""
        M1 <- corewx$M1[index]
        M1 <- if (!is.na(M1)) M1 else ""
        M2 <- corewx$M2[index]
        M2 <- if (!is.na(M2)) M2 else ""
        M3 <- corewx$M3[index]
        M3 <- if (!is.na(M3)) M3 else ""
        tagList(
          div(style = list(fontSize = 24, fontWeight = 600), value),
          div(style = list(fontSize = 10), Reading),
          div(style = list(fontSize = 9), M1),
          div(style = list(fontSize = 9), M2),
          div(style = list(fontSize = 9), M3)
        )
      },
      align = "center"
    ),

    T1 = colDef(show = FALSE),
    M1 = colDef(show = FALSE),
    M2 = colDef(show = FALSE),
    M3 = colDef(show = FALSE),
    Sentences = colDef(show = FALSE),
    Reading = colDef(show = FALSE)

  ),
  defaultPageSize = 1,
  theme = reactableTheme(
    # Vertically center cells
    cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center", height = 250, fontSize = "11px"),
    searchInputStyle = list(
      paddingLeft = "8px",
      paddingTop = "8px",
      paddingBottom = "8px",
      width = "100%"
    )
  ),
  showPageInfo = FALSE, bordered = TRUE, searchable = TRUE, paginationType = "simple",
  
  style = list(fontFamily = "Noto Sans JP, Hiragino Maru Gothic ProN, Anonymous Pro , Helvetica Neue", fontSize = "11px")
)

```

</div>

<div class = "col-sm-8">

```{r, echo=FALSE, message=FALSE}

corewz <- corew %>% slice(1:200) %>% rename(Sentences = S1)
corewz <- corewz[sample(1:nrow(corewz)),]

reactable(
  corewz,
  columns = list(
    Words = colDef(
      # Show species under character names
      cell = function(value, index) {
        Reading <- corewz$Reading[index]
        Reading <- if (!is.na(Reading)) Reading else ""
        Sentences <- corewz$Sentences[index]
        Sentences <- if (!is.na(Sentences)) Sentences else ""
        M1 <- corewz$M1[index]
        M1 <- if (!is.na(M1)) M1 else ""
        M2 <- corewz$M2[index]
        M2 <- if (!is.na(M2)) M2 else ""
        M3 <- corewz$M3[index]
        M3 <- if (!is.na(M3)) M3 else ""
        tagList(
          div(style = list(fontSize = 24, fontWeight = 600), value),
          div(style = list(fontSize = 18, fontWeight = 500), Sentences),
          # div(style = list(fontSize = 10), Reading),
          # div(style = list(fontSize = 9), M1),
          # div(style = list(fontSize = 9), M2),
          # div(style = list(fontSize = 9), M3)
        )
      },
      align = "center"
    ),

    T1 = colDef(show = FALSE),
    M1 = colDef(show = FALSE),
    M2 = colDef(show = FALSE),
    M3 = colDef(show = FALSE),
    Sentences = colDef(show = FALSE),
    Reading = colDef(show = FALSE)

  ),
  defaultPageSize = 1,
  theme = reactableTheme(
    # Vertically center cells
    cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center", height = 250, fontSize = "11px"),
    searchInputStyle = list(
      paddingLeft = "8px",
      paddingTop = "8px",
      paddingBottom = "8px",
      width = "100%"
    )
  ),
  showPageInfo = FALSE, bordered = TRUE, searchable = TRUE, paginationType = "simple",
  
  style = list(fontFamily = "Noto Sans JP, Hiragino Maru Gothic ProN, Anonymous Pro , Helvetica Neue", fontSize = "11px")
)

```

</div>
</div>

------------------------------------------------------------------------

### Common {.tabset}

<div class = "row">
<div class = "col-sm-4">

```{r, echo=FALSE, message=FALSE}

cnmw <- cnmw[sample(1:nrow(cnmw)),]

reactable(
  cnmw,
  columns = list(
    Words = colDef(
      cell = function(value, index) {
        Meaning <- cnmw$Meaning[index]
        Meaning <- if (!is.na(Meaning)) Meaning else ""
        Reading <- cnmw$Reading[index]
        Reading <- if (!is.na(Reading)) Reading else ""
        Sentences <- cnmw$Sentences[index]
        Sentences <- if (!is.na(Sentences)) Sentences else ""
        Translation <- cnmw$Translation[index]
        Translation <- if (!is.na(Translation)) Translation else ""
        tagList(
          div(style = list(fontSize = 24, fontWeight = 600), value),
          div(style = list(fontSize = 9), Reading),
          div(style = list(fontSize = 10), Meaning),
        )
      },
      align = "center"
    ),
    
    Meaning = colDef(show = FALSE),
    Reading = colDef(show = FALSE),
    Sentences = colDef(show = FALSE),
    Translation = colDef(show = FALSE)
  ),
  defaultPageSize = 1,
  theme = reactableTheme(
    cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center", fontSize = "11px", height = 250),
    searchInputStyle = list(
      paddingLeft = "8px",
      paddingTop = "8px",
      paddingBottom = "8px",
      width = "100%",
      fontSize = "11px"
    )
  ),
  showPageInfo = FALSE, bordered = TRUE, searchable = TRUE, sortable = FALSE, paginationType = "simple",

  style = list(fontFamily = "Noto Sans JP, Heiti SC, Hiragino Maru Gothic ProN, Anonymous Pro , monospace, Helvetica Neue", fontSize = "11px")
)


```

</div>

<div class = "col-sm-8">

```{r, echo=FALSE, message=FALSE}

cnmw <- cnmw[sample(1:nrow(cnmw)),]

reactable(
  cnmw,
  columns = list(
    Words = colDef(
      cell = function(value, index) {
        Meaning <- cnmw$Meaning[index]
        Meaning <- if (!is.na(Meaning)) Meaning else ""
        Reading <- cnmw$Reading[index]
        Reading <- if (!is.na(Reading)) Reading else ""
        Sentences <- cnmw$Sentences[index]
        Sentences <- if (!is.na(Sentences)) Sentences else ""
        Translation <- cnmw$Translation[index]
        Translation <- if (!is.na(Translation)) Translation else ""
        tagList(
          div(style = list(fontSize = 24, fontWeight = 600), value),
          div(style = list(fontSize = 18, fontWeight = 500), Sentences),
          # div(style = list(fontSize = 9), Reading),
          # div(style = list(fontSize = 10), Meaning),
        )
      },
      align = "center"
    ),
    
    Meaning = colDef(show = FALSE),
    Reading = colDef(show = FALSE),
    Sentences = colDef(show = FALSE),
    Translation = colDef(show = FALSE)
  ),
  defaultPageSize = 1,
  theme = reactableTheme(
    cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center", fontSize = "11px", height = 250),
    searchInputStyle = list(
      paddingLeft = "8px",
      paddingTop = "8px",
      paddingBottom = "8px",
      width = "100%",
      fontSize = "11px"
    )
  ),
  showPageInfo = FALSE, bordered = TRUE, searchable = TRUE, sortable = FALSE, paginationType = "simple",

  style = list(fontFamily = "Noto Sans JP, Heiti SC, Hiragino Maru Gothic ProN, Anonymous Pro , monospace, Helvetica Neue", fontSize = "11px")
)

```

</div>
</div>

------------------------------------------------------------------------

### Random {.tabset}
<div class = "row">
<div class = "col-sm-4">

```{r, echo=FALSE, message=FALSE}

cmwrdsn <- cmwrdsn[sample(1:nrow(cmwrdsn)),]

reactable(
  cmwrdsn,
  columns = list(
    Words = colDef(
      cell = function(value, index) {
        Note <- cmwrdsn$Note[index]
        Note <- if (!is.na(Note)) Note else ""
        tagList(
          div(style = list(fontSize = 24, fontWeight = 600), value),
          div(style = list(fontSize = 10), Note),
        )
      },
      align = "center"
    ),
    
    # Sentences = colDef(
    #   minWidth = 180,
    #   cell = function(value, index) {
    #     Remarks <- cmwrdsn$Remarks[index]
    #     Remarks <- if (!is.na(Remarks)) Remarks else ""
    #     Translation <- cmwrdsn$Translation[index]
    #     Translation <- if (!is.na(Translation)) Translation else ""
    #     tagList(
    #       div(style = list(fontSize = 16, fontWeight = 500), value),
    #       div(style = list(fontSize = 9), Translation),
    #       # div(style = list(fontSize = 9, fontWeight = 500), Remarks),
    #     )
    #   },
    #   align = "left"
    # ),
    
    Rank = colDef(show = FALSE),
    Note = colDef(show = FALSE),
    Remarks = colDef(show = FALSE),
    Sentences = colDef(show = FALSE),
    Translation = colDef(show = FALSE)
  ),
  defaultPageSize = 1,
  theme = reactableTheme(
    cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center", fontSize = "11px", height = 250),
    searchInputStyle = list(
      paddingLeft = "8px",
      paddingTop = "8px",
      paddingBottom = "8px",
      width = "100%",
      fontSize = "11px"
    )
  ),
  showPageInfo = FALSE, bordered = TRUE, searchable = TRUE, sortable = FALSE, paginationType = "simple",

  style = list(fontFamily = "Noto Sans JP, Heiti SC, Hiragino Maru Gothic ProN, Anonymous Pro , monospace, Helvetica Neue", fontSize = "11px")
)

```

</div>

<div class = "col-sm-8">

```{r, echo=FALSE, message=FALSE}

cmwrdsn <- cmwrdsn[sample(1:nrow(cmwrdsn)),]

reactable(
  cmwrdsn,
  columns = list(
    Words = colDef(
      cell = function(value, index) {
        Note <- cmwrdsn$Note[index]
        Note <- if (!is.na(Note)) Note else ""
        Sentences <- cmwrdsn$Sentences[index]
        Sentences <- if (!is.na(Sentences)) Sentences else ""
        tagList(
          div(style = list(fontSize = 24, fontWeight = 600), value),
          div(style = list(fontSize = 18, fontWeight = 500), Sentences),
        )
      },
      align = "center"
    ),
    
    Rank = colDef(show = FALSE),
    Note = colDef(show = FALSE),
    Remarks = colDef(show = FALSE),
    Sentences = colDef(show = FALSE),
    Translation = colDef(show = FALSE)
  ),
  defaultPageSize = 1,
  theme = reactableTheme(
    cellStyle = list(display = "flex", flexDirection = "column", justifyContent = "center", fontSize = "11px", height = 250),
    searchInputStyle = list(
      paddingLeft = "8px",
      paddingTop = "8px",
      paddingBottom = "8px",
      width = "100%",
      fontSize = "11px"
    )
  ),
  showPageInfo = FALSE, bordered = TRUE, searchable = TRUE, sortable = FALSE, paginationType = "simple",

  style = list(fontFamily = "Noto Sans JP, Heiti SC, Hiragino Maru Gothic ProN, Anonymous Pro , monospace, Helvetica Neue", fontSize = "11px")
)

```

</div>
</div>
